### PR TITLE
Update syntax for Python3.

### PR DESCRIPTION
**Pull request by adarnimrod**
Used 2to3 to update the syntax for Python3. Also changed the shebang to
use Python3.

### CODE REVIEW

**Comment by adarnimrod** [comment]
@sgnn7 @dbnicholson

**Comment by sgnn7** [comment]
@adarnimrod Thank you for your contribution! I should be able to check this out by next week since this project will need a bit of dusting off.

**Comment by adarnimrod** [comment]
@sgnn7 I already had a chance to run it and it ran without any issues.

**Comment by sgnn7** [comment]
> @sgnn7 I already had a chance to run it and it ran without any issues.

@adarnimrod While I appreciate the effort, the point of a pull request is that someone takes a look at the code usually and in my case that includes ensuring on my own that the code runs since this project might be used by other people. Because of this, I need to run a few smoke tests to ensure that nothing got broken here with the changes.

**Comment by sgnn7** [comment]
@adarnimrod Just letting you know that I haven't forgotten about this change - it's still in my queue to take a look at but the weekend got pretty busy for me so I'll have to do that later this week.

**Comment by adarnimrod** [comment]
@sgnn7 thanks. BTW, in https://github.com/endlessm/gh_fetch/pull/7 I updated the PR to keep Python2 compatibility (this PR breaks Python2 compatibility). Do you want me to update this PR?

**Comment by sgnn7** [comment]
@adarnimrod Yes please - that would be great! Thank you!

**Comment by adarnimrod** [comment]
@sgnn7 the PR is updated.

**Comment by sgnn7** [comment]
@adarnimrod Closing this PR in favor of #18 as it has the same history of your commits as this PR but also a fix for Python2 that I found when testing and updates the readme to add new contributors.

**Pull request closed without merging**
